const COLORS = [
  "#FF6B6B", "#4ECDC4", "#45B7D1", "#96CEB4", "#FFEAA7",
  "#DDA0DD", "#98D8C8", "#F7DC6F", "#BB8FCE", "#85C1E9",
];

/** Names auto-assigned before users could pick their own. */
const LEGACY_ADJECTIVES = [
  "Swift", "Bold", "Keen", "Bright", "Calm", "Sharp", "Quick", "Wise",
  "Cool", "Neat", "Prime", "Fresh", "Clear", "Steady", "Agile", "Solid",
];

const LEGACY_NOUNS = [
  "Falcon", "River", "Pixel", "Orbit", "Spark", "Forge", "Beacon", "Comet",
  "Anchor", "Summit", "Vector", "Pulse", "Cedar", "Nova", "Drift", "Crest",
];

function pickColor(): string {
  return COLORS[Math.floor(Math.random() * COLORS.length)]!;
}

export interface UserIdentity {
  id: string;
  name: string;
  color: string;
  /** True when the user typed their name in the join prompt. */
  chosenByUser?: boolean;
}

const STORAGE_KEY = "boardroom-identity";

export function isLegacyAutoGeneratedName(name: string): boolean {
  const parts = name.trim().split(/\s+/);
  if (parts.length !== 2) return false;
  return (
    LEGACY_ADJECTIVES.includes(parts[0]!) && LEGACY_NOUNS.includes(parts[1]!)
  );
}

function clearStoredIdentity(): void {
  if (typeof window === "undefined") return;
  sessionStorage.removeItem(STORAGE_KEY);
}

export function getStoredIdentity(): UserIdentity | null {
  if (typeof window === "undefined") return null;
  const stored = sessionStorage.getItem(STORAGE_KEY);
  if (!stored) return null;
  try {
    const parsed = JSON.parse(stored) as UserIdentity;
    if (!parsed.id || !parsed.name?.trim()) {
      clearStoredIdentity();
      return null;
    }
    // Old sessions auto-assigned random names — ask again.
    if (!parsed.chosenByUser || isLegacyAutoGeneratedName(parsed.name)) {
      clearStoredIdentity();
      return null;
    }
    return parsed;
  } catch {
    clearStoredIdentity();
    return null;
  }
}

export function saveIdentity(name: string, previous?: UserIdentity | null): UserIdentity {
  const trimmed = name.trim();
  const existing = previous ?? getStoredIdentity();
  const identity: UserIdentity = {
    id: existing?.id ?? `user-${Math.random().toString(36).slice(2, 10)}`,
    name: trimmed,
    color: existing?.color ?? pickColor(),
    chosenByUser: true,
  };
  sessionStorage.setItem(STORAGE_KEY, JSON.stringify(identity));
  return identity;
}

export function getInitials(name: string): string {
  return name
    .split(" ")
    .map((w) => w[0])
    .join("")
    .toUpperCase()
    .slice(0, 2);
}
